seed: 0

datasets:
  co3d:
    split: test
    co3d_dir: workspace/benchmark_dataset/co3dv2/vggt_testset
    co3d_anno_dir: workspace/benchmark_dataset/co3dv2/vggt_anno_10frames_1seq_rand
    categories: Null    # Set to Null to evaluate all categories
    min_num_images: 50
    num_frames: 10
    use_ba: False
    debug: False        # Set to False to evaluate all categories
    fast_eval: True     # Only evaluate 10 sequences per category
    disable_rand: True  # Set to True if each category folder under co3d_dir has already been filtered to 10 images; all found images will be used for evaluation

  re10k:
    re10k_dir: workspace/benchmark_dataset/realestate10k/data/re10k
    re10k_meta_path: workspace/benchmark_dataset/realestate10k/datasets/seq-id-maps/Re10K_relpose_seq-id-map_seed42.json
    scenes: Null  # Set to Null to use all scenes
    use_ba: False

  7scenes:
    scenes: ["chess", "fire", "heads", "office", "pumpkin", "redkitchen", "stairs"]
    sample_mode: uniform  # uniform vs. random sampling of frames
    max_frames: 128
    eval_tasks: [pose, depth, recon_unposed]

  eth3d:
    scenes: [
      "courtyard", "electro", "kicker", "pipes", "relief", "delivery_area",
      "facade", "office", "playground", "relief_2", "terrains",
    ]
    sample_mode: uniform
    max_frames: 128
    eval_tasks: [pose, depth, recon_unposed]

  scannetpp:
    scenes: [
      "09c1414f1b", "1ada7a0617", "40aec5fffa", "3e8bba0176", "acd95847c5",
      "578511c8a9", "5f99900f09", "c4c04e6d6c", "f3d64c30f8", "7bc286c1b6",
      "c5439f4607", "286b55a2bf", "fb5a96b1a2", "7831862f02", "38d58a7a31",
      "bde1e479ad", "9071e139d9", "21d970d8de", "bcd2436daf", "cc5237fd77",
    ]
    sample_mode: uniform
    max_frames: 128
    eval_tasks: [pose, depth, recon_unposed]

  hiroom:
    scenes: Null  # Set to Null to use all scenes
    sample_mode: uniform
    max_frames: 128
    eval_tasks: [pose, depth, recon_unposed]

  dtu64:
    scenes: [
      "scan105", "scan114", "scan118", "scan122", "scan24",
      "scan37", "scan40", "scan55", "scan63", "scan65",
      "scan69", "scan83", "scan97",
    ]
    sample_mode: uniform
    max_frames: 128
    eval_tasks: [pose]  # NOTE: only `pose` is supported

  dtu:
    scenes: [
      "scan1", "scan4", "scan9", "scan10", "scan11", "scan12",
      "scan13", "scan15", "scan23", "scan24", "scan29", "scan32",
      "scan33", "scan34", "scan48", "scan49", "scan62", "scan75",
      "scan77", "scan110", "scan114", "scan118",
    ]
    sample_mode: uniform
    max_frames: 128
    eval_tasks: [recon_unposed]  # NOTE: only `recon_unposed` is supported

  scannet:
    scannet_dir: workspace/benchmark_dataset/scannetv2/scans
    scenes: Null                 # Null to use all scenes
    sample_mode: uniform         # uniform | stride
    step_size: 5                 # Only used if sample_mode=stride; Sample every step_size frames
    max_frames: 128
    # NOTE: the default value from FastVGGT is 3.0 which is too strict and causes lots of NaN values and skipped scenes
    depth_conf_thresh: 1.0       # Depth confidence threshold for filtering low confidence depth values
    chamfer_max_dist: 0.5        # Maximum distance threshold for Chamfer distance
    plot: False                  # Whether to generate plots during evaluation
    plot_dir: tmp_plots/scannet_${.max_frames}  # Directory to save plots
  
  