defaults:
  - default_datasets.yaml
  - _self_


model:
  name: StreamVGGT
  ckpt_path: checkpoints/streamvggt/checkpoints.pth


# Selected datasets for evaluation.
# Detailed configurations for each dataset can be set below.
selected_datasets: [7scenes, eth3d, scannetpp, hiroom, dtu64]

datasets:
  co3d:
    debug: False
    fast_eval: True
    disable_rand: True

  7scenes:
    max_frames: 128
    eval_tasks: [pose, depth]

  eth3d:
    max_frames: 128
    eval_tasks: [pose, depth]

  scannetpp:
    max_frames: 128
    eval_tasks: [pose, depth]

  hiroom:
    max_frames: 128
    eval_tasks: [pose, depth]

  dtu:
    max_frames: 128
    eval_tasks: [pose]

  scannet:
    max_frames: 300
    sample_mode: uniform
    plot: True
    plot_dir: tmp_plots/scannet_${.max_frames}
